'use strict';

/**
 * Static site generator. Writes a complete dist/ directory: every page as
 * pre-rendered HTML (no client-side routing, no runtime data fetch), the
 * two browser client modules, the pure page-range parser (also loaded
 * client-side), the self-hosted vendor libraries, and the identity/SEO
 * files (sitemap.xml, robots.txt, ads.txt, favicon, og-image).
 *
 * Usage: npm run build
 */

const fs = require('fs');
const path = require('path');

const { copyVendor } = require('../scripts/copy-vendor.js');
const { renderHomePage } = require('./pages/home.js');
const { renderHowThisWorksPage } = require('./pages/howThisWorks.js');
const { renderPrivacyPage } = require('./pages/privacy.js');
const { renderToolPage } = require('./pages/toolPage.js');
const { renderFolderPage, renderDataIndexPage } = require('./pages/folder.js');
const { render404Page } = require('./pages/notFound.js');
const { TOOLS } = require('./tools/index.js');
const { FOLDERS } = require('./folders.js');
const { sitemapPathsFor, renderSitemapXml, robotsTxtContent } = require('./sitemap.js');
const { renderRssXml } = require('./rss.js');
const { INDEXNOW_KEY } = require('./indexnow.js');
const { ICON_SVG } = require('./icon.js');
const { assembleBrowserClients } = require('./browserClients.js');

/**
 * The browser-facing counterpart of src/browserClients.js's assembly: a
 * plain ES module text (2026-08-22 fragment-pattern refactor) providing
 * exactly the PROCESSORS/MAX_BYTES_BY_CLIENT/PASTE_FILE shape
 * src/browser/dropzone.client.js used to hand-type as top-level consts.
 * Written into dist/js/ alongside dropzone.client.js's own copy (never
 * checked into git, like everything else under dist/) so its relative
 * `import './dropzone.registry.generated.js'` resolves. Kept as generated
 * text rather than a shared runtime module because dropzone.client.js is a
 * plain browser ES module with no bundler and no build step of its own
 * (see that file's header comment) -- PROCESSORS' values are functions
 * that each need a real, static `import('./X.client.js')` call, which
 * only generated source text (not JSON) can express.
 */
function renderDropzoneRegistry(clientFiles, maxBytesByClient, pasteFile) {
  const processorLines = clientFiles
    .map((file) => file.replace(/\.client\.js$/, ''))
    .map((clientEntry) => `  ${clientEntry}: () => import('./${clientEntry}.client.js'),`)
    .join('\n');
  return `// AUTO-GENERATED by src/build.js's renderDropzoneRegistry(), from the
// TOOLS registry (src/tools/*.js) -- do not hand-edit. See
// src/browser/dropzone.client.js's header comment.

export const PROCESSORS = {
${processorLines}
};

export const MAX_BYTES_BY_CLIENT = ${JSON.stringify(maxBytesByClient, null, 2)};

export const PASTE_FILE = ${JSON.stringify(pasteFile, null, 2)};
`;
}

const ROOT = path.join(__dirname, '..');
const OUT_DIR = path.join(ROOT, 'dist');
const ASSETS_DIR = path.join(ROOT, 'assets');

function rimraf(dir) {
  fs.rmSync(dir, { recursive: true, force: true });
}

function writeHtml(relDirPath, html) {
  const dir = path.join(OUT_DIR, relDirPath);
  fs.mkdirSync(dir, { recursive: true });
  fs.writeFileSync(path.join(dir, 'index.html'), html, 'utf8');
}

function copyDir(from, to) {
  fs.mkdirSync(to, { recursive: true });
  for (const entry of fs.readdirSync(from, { withFileTypes: true })) {
    const src = path.join(from, entry.name);
    const dest = path.join(to, entry.name);
    if (entry.isDirectory()) copyDir(src, dest);
    else fs.copyFileSync(src, dest);
  }
}

function adsTxtContent() {
  return `# ads.txt for filetools\n# Declares authorized sellers of this site's ad inventory.\n# See https://iabtechlab.com/ads-txt/ for the spec.\ngoogle.com, pub-9767914878112531, DIRECT, f08c47fec0942fa0\n`;
}

async function build() {
  rimraf(OUT_DIR);
  fs.mkdirSync(OUT_DIR, { recursive: true });

  // Real, generated (not drawn) per-tool output-example panels -- see
  // src/examples/index.mjs's header comment. This is the one place
  // build() is async: everything else here is synchronous CJS, but
  // loading an ESM module (src/examples/*.mjs, which import the pure
  // ESM src/pure/*.mjs modules to compute a real result at build time)
  // from CommonJS requires a dynamic import(). Resolved once, up front,
  // not per tool page.
  const { exampleFor, ariaLabelFor, noteFor } = await import('./examples/index.mjs');

  // 1. Pages
  writeHtml('', renderHomePage());
  writeHtml('how-this-works', renderHowThisWorksPage());
  writeHtml('privacy', renderPrivacyPage());
  TOOLS.forEach((tool) => {
    const exampleHtml = exampleFor(tool.slug);
    writeHtml(path.join(tool.category, tool.slug), renderToolPage(tool, {
      exampleHtml,
      exampleAriaLabel: ariaLabelFor(tool.slug),
      exampleNote: noteFor(tool.slug),
    }));
  });
  // Folder index pages + the noindex /data/ helper page (site-wide
  // navigation/IA redesign) -- derived from FOLDERS (src/folders.js),
  // never hand-listed.
  FOLDERS.forEach((folder) => {
    writeHtml(folder.slug, renderFolderPage(folder));
  });
  writeHtml('data', renderDataIndexPage());
  fs.writeFileSync(path.join(OUT_DIR, '404.html'), render404Page(), 'utf8');

  // 2. Browser client modules -> dist/js/ (2026-08-22 fragment-pattern
  // refactor: per-tool client files used to be one hand-typed
  // fs.copyFileSync line each; now derived from CLIENT_FILES, itself
  // assembled from every tool's own `clientEntry` field --
  // src/browserClients.js. dropzone.client.js (the page-agnostic
  // controller) and newsletter.client.js (unrelated to any tool -- footer
  // signup) are the only two files that are NOT per-tool, so they stay a
  // fixed pair here rather than living in any tool's fragment.
  const jsDir = path.join(OUT_DIR, 'js');
  fs.mkdirSync(jsDir, { recursive: true });
  const { CLIENT_FILES, MAX_BYTES_BY_CLIENT, PASTE_FILE } = assembleBrowserClients();
  // regexTester.worker.js: the regex tester's own Web Worker (see that
  // file's header comment for why matching runs off the main thread) --
  // not a per-tool `<slug>.client.js` CLIENT_FILES already copies (it's
  // never referenced by a <script> tag, only by regexTester.client.js's
  // own `new Worker(...)` call), so it needs the same fixed-list treatment
  // dropzone.client.js/newsletter.client.js get.
  // batchProgress.js: the shared determinate-batch-progress formatter/
  // reporter (src/browser/batchProgress.js's own header comment) -- plain
  // ES-module `import`ed by name from a handful of per-tool client files
  // (imagesToPdf/pdfToImages/pdfImageExtract), never itself a tool's
  // `clientEntry`, so CLIENT_FILES never picks it up on its own -- same
  // fixed-list treatment as the other shared, non-per-tool files here.
  //
  // compareCsvPro.client.js: Compare-CSV Pro's own controller
  // (the compare-csv paid batch/Excel-report add-on) -- same category as regexTester.worker.js/
  // filter.client.js above, not a per-tool CLIENT_FILES entry, since it's
  // loaded by its own fixed <script> tag (src/pages/toolPage.js's
  // proFeatureHtml) rather than routed through dropzone.client.js's
  // PROCESSORS map by clientEntry/maxBytes.
  const ALWAYS_COPY_CLIENT_FILES = ['dropzone.client.js', 'newsletter.client.js', 'regexTester.worker.js', 'filter.client.js', 'batchProgress.js', 'compareCsvPro.client.js'];
  for (const file of [...ALWAYS_COPY_CLIENT_FILES, ...CLIENT_FILES]) {
    fs.copyFileSync(path.join(ROOT, 'src', 'browser', file), path.join(jsDir, file));
  }

  // 2b. dropzone.registry.generated.js -- the browser-facing PROCESSORS/
  // MAX_BYTES_BY_CLIENT/PASTE_FILE maps dropzone.client.js imports (see
  // that file's header comment and renderDropzoneRegistry() above).
  // Written from the exact same CLIENT_FILES/MAX_BYTES_BY_CLIENT/
  // PASTE_FILE this step already computed, so the two can never drift.
  fs.writeFileSync(path.join(jsDir, 'dropzone.registry.generated.js'), renderDropzoneRegistry(CLIENT_FILES, MAX_BYTES_BY_CLIENT, PASTE_FILE), 'utf8');

  // 3. Pure modules also loaded client-side -> dist/pure/. Derived by
  // scanning every copied per-tool client file's own dynamic
  // import('../pure/X.mjs') calls, rather than a separate hand-typed copy
  // list -- a client file's own source is the one place its pure-module
  // dependencies can never drift from the truth, so a new tool's client
  // file needs no separate pure-module declaration at all.
  const pureDir = path.join(OUT_DIR, 'pure');
  fs.mkdirSync(pureDir, { recursive: true });
  const pureModules = new Set();
  // Also scans ALWAYS_COPY_CLIENT_FILES (not just CLIENT_FILES): regexTester.worker.js
  // is the one file in that list that itself imports a pure module
  // (regexTester.client.js hands its actual matching work off to the
  // worker rather than importing the pure module directly -- see that
  // worker's header comment), so its own pure-module dependency has to be
  // discovered the same way any client file's is.
  for (const file of [...CLIENT_FILES, ...ALWAYS_COPY_CLIENT_FILES]) {
    const src = fs.readFileSync(path.join(ROOT, 'src', 'browser', file), 'utf8');
    for (const m of src.matchAll(/\.\.\/pure\/([\w.-]+\.mjs)/g)) pureModules.add(m[1]);
  }
  for (const file of [...pureModules].sort()) {
    fs.copyFileSync(path.join(ROOT, 'src', 'pure', file), path.join(pureDir, file));
  }

  // 4. Vendor libraries (pdf-lib, pdfjs-dist, exceljs, fflate) -> dist/vendor/
  copyVendor();
  copyDir(path.join(ROOT, 'vendor'), path.join(OUT_DIR, 'vendor'));

  // 5. Identity assets: favicon.svg always generated fresh from icon.js;
  // apple-touch-icon.png / og-default.png are pre-generated by
  // scripts/build-og-image.js (a Playwright script, not part of the plain
  // static build); google679d03facc8b0931.html is a Search Console
  // site-verification file that must keep serving at the site root
  // indefinitely, even after verification succeeds -- do not remove it.
  // All three are just copied in here if present.
  fs.writeFileSync(path.join(OUT_DIR, 'favicon.svg'), ICON_SVG, 'utf8');
  if (fs.existsSync(ASSETS_DIR)) {
    for (const file of ['og-default.png', 'apple-touch-icon.png', 'google679d03facc8b0931.html']) {
      const src = path.join(ASSETS_DIR, file);
      if (fs.existsSync(src)) fs.copyFileSync(src, path.join(OUT_DIR, file));
    }
  }

  // 6. sitemap.xml / robots.txt / ads.txt, derived from what was actually
  // written above.
  const sitemapPaths = sitemapPathsFor(TOOLS);
  fs.writeFileSync(path.join(OUT_DIR, 'sitemap.xml'), renderSitemapXml(sitemapPaths), 'utf8');
  fs.writeFileSync(path.join(OUT_DIR, 'robots.txt'), robotsTxtContent(), 'utf8');
  fs.writeFileSync(path.join(OUT_DIR, 'ads.txt'), adsTxtContent(), 'utf8');

  // 6b. IndexNow key file -- IndexNow (Bing/Yandex/Naver/Seznam/Yep) proves
  // this site's ownership of a ping by finding the exact key it was pinged
  // with at <key>.txt on the site root (indexnow.org/documentation). The
  // key itself lives in src/indexnow.js so scripts/indexnow-ping.js (run
  // post-deploy in CI) can never send a key that doesn't match this file.
  fs.writeFileSync(path.join(OUT_DIR, `${INDEXNOW_KEY}.txt`), `${INDEXNOW_KEY}\n`, 'utf8');

  // 7. feed.xml -- RSS of tool launches (see src/rss.js's header comment).
  fs.writeFileSync(path.join(OUT_DIR, 'feed.xml'), renderRssXml(TOOLS), 'utf8');

  console.log(`Built ${TOOLS.length + FOLDERS.length + 4} pages plus 404.html into dist/.`);
}

if (require.main === module) {
  build().catch((e) => {
    console.error(e);
    process.exitCode = 1;
  });
}

module.exports = { build };
